BrainDump/Models/Issue.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;


namespace BrainDump.Models
{
    public class Issue
    {
        public int Id { get; set; }

        [StringLength(120, MinimumLength = 3)]
        [Required]
        public string Title { get; set; }

        [RegularExpression(@"^[A-Za-z]\w*-\d+$")]
        [Required]
        public string IssueId { get; set; }

        [Display(Name = "Creation Date")]
        [DataType(DataType.DateTime)]
        public DateTime CreationDate { get; set; }
        public string Description { get; set; }

        //[Comment("link to an epic")]
        public string Epic { get; set; }

        public string Module { get; set; }

        public string Assignee { get; set; }

        public string State { get; set; }

        public string Labels { get; set; }

        public string Link { get; set; }

        public string Priority { get; set; }
    }
}

BrainDump/Controllers/IssuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrainDump.Data;
using BrainDump.Models;

namespace BrainDump.Controllers
{
    public class IssuesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IssuesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Issues
        public async Task<IActionResult> Index(string label, string searchString)
        {
            IQueryable<string> labelQuery = from m in _context.Issue
                                            orderby m.Labels
                                            select m.Labels;

            var issues = from m in _context.Issue
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                issues = issues.Where(s => s.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(label))
            {
                issues = issues.Where(x => x.Labels == label);
            }

            var issueWithLabelVM = new IssueLabelViewModel
            {
                Labels = new SelectList(await labelQuery.Distinct().ToListAsync()),
                Issues = await issues.ToListAsync()
            };

            return View(issueWithLabelVM);

        }

        // GET: Issues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issue
                .FirstOrDefaultAsync(m => m.Id == id);
            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // GET: Issues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Issues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IssueId,Title,CreationDate,Description,Epic,Module,Assignee,State,Labels,Link,Priority")] Issue issue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(issue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(issue);
        }

        // GET: Issues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issue.FindAsync(id);
            if (issue == null)
            {
                return NotFound();
            }
            return View(issue);
        }

        // POST: Issues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IssueId,Title,CreationDate,Description,Epic,Module,Assignee,State,Labels,Link,Priority")] Issue issue)
        {
            if (id != issue.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(issue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IssueExists(issue.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(issue);
        }

        // GET: Issues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issue
                .FirstOrDefaultAsync(m => m.Id == id);
            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // POST: Issues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var issue = await _context.Issue.FindAsync(id);
            _context.Issue.Remove(issue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IssueExists(int id)
        {
            return _context.Issue.Any(e => e.Id == id);
        }
    }
}

BrainDump/Views/Issues/Create.cshtml
@model BrainDump.Models.Issue

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Issue</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueId" class="control-label"></label>
                <input asp-for="IssueId" class="form-control" />
                <span asp-validation-for="IssueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Epic" class="control-label"></label>
                <input asp-for="Epic" class="form-control" />
                <span asp-validation-for="Epic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Module" class="control-label"></label>
                <input asp-for="Module" class="form-control" />
                <span asp-validation-for="Module" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assignee" class="control-label"></label>
                <input asp-for="Assignee" class="form-control" />
                <span asp-validation-for="Assignee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Labels" class="control-label"></label>
                <input asp-for="Labels" class="form-control" />
                <span asp-validation-for="Labels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BrainDump/Views/Issues/Delete.cshtml
@model BrainDump.Models.Issue

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Issue</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Epic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Epic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Module)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Module)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assignee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assignee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Labels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Labels)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BrainDump/Views/Issues/Details.cshtml
@model BrainDump.Models.Issue

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Issue</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IssueId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IssueId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Epic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Epic)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Module)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Assignee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Assignee)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Labels)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Labels)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BrainDump/Views/Issues/Edit.cshtml
@model BrainDump.Models.Issue

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Issue</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueId" class="control-label"></label>
                <input asp-for="IssueId" class="form-control" />
                <span asp-validation-for="IssueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Epic" class="control-label"></label>
                <input asp-for="Epic" class="form-control" />
                <span asp-validation-for="Epic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Module" class="control-label"></label>
                <input asp-for="Module" class="form-control" />
                <span asp-validation-for="Module" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assignee" class="control-label"></label>
                <input asp-for="Assignee" class="form-control" />
                <span asp-validation-for="Assignee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Labels" class="control-label"></label>
                <input asp-for="Labels" class="form-control" />
                <span asp-validation-for="Labels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BrainDump/Views/Issues/Index.cshtml
@model BrainDump.Models.IssueLabelViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Issues" asp-action="Index" method="get">
    <p>
        <select asp-for="Label" asp-items="Model.Labels">
            <option value="">All</option>
        </select>

        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].IssueId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Epic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Module)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Assignee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Labels)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Issues[0].Priority)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Issues) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssueId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Epic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Module)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Assignee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Labels)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>